/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package client;

import java.time.Duration;

import com.uber.cadence.client.WorkflowClient;
import com.uber.cadence.client.WorkflowClientOptions;
import com.uber.cadence.client.WorkflowOptions;
import com.uber.cadence.serviceclient.ClientOptions;
import com.uber.cadence.serviceclient.WorkflowServiceTChannel;

import workflow.common.OrdersWorkflow;
import workflow.common.domain.Order;

public class App {
        public static final String HOST = "lb-4cb3bc1e-a8a5-40eb-a031-98c99-8a839478a0563d5b.elb.us-west-2.amazonaws.com";
        public static final String DOMAIN = "samples-domain";
        public static final String TASK_LIST = "orders-task-list-java";

        public static void main(String[] args) {
                WorkflowOptions workflowOptions = new WorkflowOptions.Builder()
                                .setExecutionStartToCloseTimeout(Duration.ofMinutes(5))
                                .setTaskList(App.TASK_LIST)
                                .build();
                WorkflowClient workflowClient = WorkflowClient.newInstance(
                                new WorkflowServiceTChannel(ClientOptions.newBuilder()
                                                .setHost(App.HOST)
                                                .setPort(7933)
                                                .build()),
                                WorkflowClientOptions.newBuilder().setDomain(App.DOMAIN).build());

                OrdersWorkflow ordersWorkflow = workflowClient.newWorkflowStub(OrdersWorkflow.class, workflowOptions);

                Order inStockOrder = new Order("asdx", "email", "address");

                Order outOfStockOrder = new Order("asd", "email", "address");

                WorkflowClient.start(ordersWorkflow::processOrder, outOfStockOrder);
        }
}